url: http://ku1ik.com
title: Odes of the Occult
author: Marcin Kulik
markdown: redcarpet
highlighter: pygments
download_prefix: "http://dl.dropbox.com/u/12119988/blog"
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - bin
  - config.ru
