--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_combined
output_dir: output

deploy:
  default:
    dst:     "sickill.net:/var/www/sickill.net"
    options: [ '-gpPrvzL', '--exclude=".svn"' ]

