--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_combined
output_dir: public

base_url: http://sickill.net

deploy:
  default:
    dst:     "sickill.net:/var/www/sickill.net"
    options: [ '-gprzLv', '--exclude=".svn"' ]

